/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:9204260f-7666-4060-b4d2-fa38badbed81",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_sNH3KJ9ha",
    "aws_user_pools_web_client_id": "4fu15ab3qitjsdsirrkgflblli",
    "oauth": {}
};


export default awsmobile;
